### ISSUE TITLE
Crash on fireball to ghast

### ISSUE THREAD

**Issue by KJP12** [the-glitch-network/plymouth-fabric#7]
## Description
Hitting the fireball back to the ghast produces the following crash:

```
---- Minecraft Crash Report ----
// Sorry :(

Time: 6/12/21, 5:55 AM
Description: Ticking entity

java.lang.NullPointerException: Cannot invoke "net.kjp12.plymouth.database.Target.ply$name()" because "cause" is null
        at net.kjp12.plymouth.database.records.BlockRecord.<init>(BlockRecord.java:71)
        at net.kjp12.plymouth.database.PlymouthSQL.breakBlock(PlymouthSQL.java:248)
        at net.minecraft.class_1927.handler$zkd000$plymouth$affectWorld$onSetBlock(class_1927.java:1552)
        at net.minecraft.class_1927.method_8350(class_1927.java:275)
        at net.minecraft.class_3218.method_8454(class_3218.java:909)
        at net.minecraft.class_1937.method_8537(class_1937.java:499)
        at net.minecraft.class_1674.method_7488(class_1674.java:32)
        at net.minecraft.class_1668.method_5773(class_1668.java:76)
        at net.minecraft.class_3218.method_18762(class_3218.java:656)
        at net.minecraft.class_1937.method_18472(class_1937.java:483)
        at net.minecraft.class_3218.method_31420(class_3218.java:418)
        at net.minecraft.class_5574.method_31791(class_5574.java:54)
        at net.minecraft.class_3218.method_18765(class_3218.java:393)
        at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:893)
        at net.minecraft.class_3176.method_3813(class_3176.java:334)
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:833)
        at net.minecraft.server.MinecraftServer.handler$zno000$modifiedRunLoop(MinecraftServer.java:4393)
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:671)
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:274)
        at java.base/java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
        at net.kjp12.plymouth.database.records.BlockRecord.<init>(BlockRecord.java:71)
        at net.kjp12.plymouth.database.PlymouthSQL.breakBlock(PlymouthSQL.java:248)
        at net.minecraft.class_1927.handler$zkd000$plymouth$affectWorld$onSetBlock(class_1927.java:1552)
        at net.minecraft.class_1927.method_8350(class_1927.java:275)
        at net.minecraft.class_3218.method_8454(class_3218.java:909)
        at net.minecraft.class_1937.method_8537(class_1937.java:499)
        at net.minecraft.class_1674.method_7488(class_1674.java:32)
        at net.minecraft.class_1668.method_5773(class_1668.java:76)
        at net.minecraft.class_3218.method_18762(class_3218.java:656)

-- Entity being ticked --
Details:
        Entity Type: minecraft:fireball (net.minecraft.class_1674)
        Entity ID: 628839
        Entity's Exact location: -24.75, 73.56, 153.45
        Entity's Block location: World: (-25,73,153), Section: (at 7,9,9 in -2,4,9; chunk contains blocks -32,0,144 to -17,255,159), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
        Entity's Momentum: 1.14, 1.12, 0.02
        Entity's Passengers: []
        Entity's Vehicle: null
Stacktrace:
        at net.minecraft.class_1937.method_18472(class_1937.java:483)
        at net.minecraft.class_3218.method_31420(class_3218.java:418)
        at net.minecraft.class_5574.method_31791(class_5574.java:54)
        at net.minecraft.class_3218.method_18765(class_3218.java:393)
```

**Comment by KJP12** [comment]
Fixed in beta.4.
